use_frameworks!

target 'SwiftTesting_Example' do
  pod 'SwiftTesting', :path => '../'

  target 'SwiftTesting_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
